/**
 * DEVELOPMENT WEBPACK CONFIGURATION
 */

const path = require("path");
const webpack = require("webpack");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const CircularDependencyPlugin = require("circular-dependency-plugin");

module.exports = require("./webpack.base.babel")({
  mode: "development",

  // Add hot reloading in development
  entry: [
    require.resolve("react-app-polyfill/ie11"),
    `webpack-dev-server/client?http://localhost:3000/`,
    "webpack/hot/only-dev-server",
    path.join(process.cwd(), "app/app.js") // Start with js/app.js
  ],

  // Don't use hashes in dev mode for better performance
  output: {
    filename: "[name].js",
    chunkFilename: "[name].chunk.js",
    publicPath: `http://localhost:3000/`
  },

  optimization: {
    splitChunks: {
      chunks: "all"
    }
  },

  devServer: {
    port: 3000,
    publicPath: `http://localhost:3000/`,
    compress: true,
    noInfo: false,
    stats: "errors-only",
    inline: true,
    lazy: false,
    hot: true,
    open: true,
    overlay: true,
    headers: { "Access-Control-Allow-Origin": "*" },
    contentBase: path.join(__dirname, "..", "..", "app", "build"),
    watchOptions: {
      aggregateTimeout: 300,
      ignored: /node_modules/,
      poll: 100
    },
    historyApiFallback: {
      verbose: true,
      disableDotRule: false
    },
    proxy: {
      "/api/**": { target: "http://localhost:8080", secure: false }
    }
  },

  // Add development plugins
  plugins: [
    new webpack.HotModuleReplacementPlugin(), // Tell webpack we want hot reloading
    new HtmlWebpackPlugin({
      inject: true, // Inject all files that are generated by webpack, e.g. bundle.js
      template: "app/index.html"
    }),
    new CircularDependencyPlugin({
      exclude: /a\.js|node_modules/, // exclude node_modules
      failOnError: false // show a warning when there is a circular dependency
    })
  ],

  // Emit a source map for easier debugging
  // See https://webpack.js.org/configuration/devtool/#devtool
  devtool: "eval-source-map",

  performance: {
    hints: false
  }
});
